dict_names = {
 'ETOPO_1deg':'topography',
 'G_d_2yng_r': 'dist. to young rift',
 'G_heat_pro': 'heat production provinces',
 'WGM2012_Bo': 'Bougeur gravity anom.',
 'age'       : 'age',
 'crusthk_cr': 'crustal thickness',
 'd2_transfo': 'dist. to transform ridge',
 'd_2hotspot': 'dist. to hotspots',
 'd_2ridge'  : 'dist. to ridge',
 'd_2trench' : 'dist. to trench',
 'd_2volcano': 'dist. to volcano', 
 'litho_asth': 'lithos.-aesthenos. boundary',
 'magnetic_M': 'magnetic anomaly',
 'moho_GReD' : 'depth to Moho',
 'thk_mid_cr': 'thickness of middle crust',
 'thk_up_cru': 'thickness of upper crust',
 'upman_den_': 'upper mantle density anomaly',
 'G_u_m_vel_': 'upper mantle vel. structure',
 'lthlgy_mod': 'rock type',
 'G_ther_age': 'age of last thermo-tectonic event'
}
